### ISSUE TITLE
pls how do i use NBitcoin Altcoins for Dodgecoin & Bitcoin Cash Spend & Transaction?

### ISSUE THREAD

**Issue by sergeibystrov** [MetacoSA/NBitcoin#1116]

**Comment by NicolasDorier** [comment]
Exactly the same as Bitcoin but you pass `Altcoins.AltNetworkSets.Dogecoin.Mainnet` instead of `Network.Main` everywhere and ref the `NBitcoin.Altcoins` package.

See https://programmingblockchain.gitbook.io/programmingblockchain/ for understanding this library.

Advise you to use https://github.com/dgarage/NBXplorer/ to make things easier.
