### ISSUE TITLE
Silent Payments (bip0352) with NBitcoin

### ISSUE THREAD

**Issue by dangershony** [MetacoSA/NBitcoin#1240]
Before I dig in to this, did anyone attempt to implement Silent Payments using NBitcoin?
I assume the cryptographic functionality of addition and multiplication of EC keys is in in place to be able to implement the bip0352.

I need a similar approach in Angor in order to break the link between a project address and the angor key

**Comment by lontivero** [comment]
I started to implement it in Wasabi. The crypto is done and I can push it if you want to reuse it.

**Comment by lontivero** [comment]
I've just push what I have just in case you find it reusable. The files are:

* https://github.com/WalletWasabi/WalletWasabi/blob/484dfecd8979df6dbf4cb45845454bf372b5354a/WalletWasabi/Wallets/SilentPayment/SilentPayment.cs which implements the crypto 

* https://github.com/WalletWasabi/WalletWasabi/blob/484dfecd8979df6dbf4cb45845454bf372b5354a/WalletWasabi/Wallets/SilentPayment/SilentPaymentAddress.cs which implements the silent payment address (en|de)coding

* https://github.com/WalletWasabi/WalletWasabi/blob/484dfecd8979df6dbf4cb45845454bf372b5354a/WalletWasabi.Tests/UnitTests/Wallet/SilentPaymentTests.cs which runs implements the official test vectors (two or three of them had been removed because do not apply to Wasabi)

All this is working but it is not ready (it is still a WIP).

**Comment by dangershony** [comment]
Amazing, I really just need the simple case

Receive:
```
Let P = B + hash(a·B)·G
Encode P as a P2WPK output
``` 
Spend:
```
Let p = b + hash(A·b)·G
```

Where P will be the address of the Angor project identifier

**Comment by lontivero** [comment]
```
Let P = B + hash(a·B)·G
Encode P as a P2WPK output
```

P is an XOnlyPubKey and it i only for P2TR. All SP are TR, never WPKH.

Anyway, all the crypto is there.

**Comment by dangershony** [comment]
Can I not use P as a regular pubkey though to generate a WPKH?

**Comment by lontivero** [comment]
Yes, ofc you can but no wallet will recognize your payments and nobody will be able to pay you.

**Comment by dangershony** [comment]
Ah ok that's fine, this is not to be used by wallets.
Just wanted to make sure there is no cryptographic limitation 
Thanks for the help.

**Comment by dangershony** [comment]
Issue resolved
