### ISSUE TITLE
Using foreach with Collections

### ISSUE THREAD

**Issue by 21E14** [MetacoSA/NBitcoin#149]
Would it make sense to use foreach with collections instead of the old-school for loops i.e.:
foreach(var i in tx.Inputs) instead of for(int i = 0 ; i < tx.Inputs.Count ; i++)?

**Comment by NicolasDorier** [comment]
When I do that it is because I need the index `i` somewhere.
I have the method `tx.Inputs.AsIndexedInputs()` so I can use foreach while getting `ì`, but the problem of doing that is that for some application which index the whole blockchain, this strain the garbage collector a lot. (because I create one new object per input)

**Comment by 21E14** [comment]
Say, in the case of public bool HaveInputs(Transaction tx)) the 'i' is used strictly to retrieve a transaction input, where a var i in tx.Inputs would do. Optimizing for performance, of course, is a very different consideration.

**Comment by NicolasDorier** [comment]
if I for a for loop without needing the 'i' then this should be rewritten yes.

I'll merge PR for that

**Comment by 21E14** [comment]
PR #150 has now been added for TxIn collections.
