### ISSUE TITLE
Bouncycastle 1.8.1

### ISSUE THREAD

**Issue by andbene72** [MetacoSA/NBitcoin#151]
Hi Nicolas,

I have verified the differences between BC 1.8 and 1.8.1 and I think it's worth to replace with new source code. 
The main reason is a better support of portability
- PORTABLE conditional compilation symbol was added
- things like StartsWith are centralized in Platform class
Also there is some performance optimization.

Currently I have already a version that fully compile, I have winmerged it and now I'm testing it.
Before committing it, I would like to know where is the change you have implemented to emulate OpenSSL bugs. I have tried to look for it in previous commit but I don't find a specific commit and the early one of 6 nov are pretty big to find something without knowing which file contains this "bug". https://github.com/MetacoSA/NBitcoin/commits/master/NBitcoin.BouncyCastle

Also have you considered to change the bouncycastle project in a shared project ? In this way we have only one project (valid for portable and not) and one dll as result. 

Andrea

**Comment by NicolasDorier** [comment]
> Also have you considered to change the bouncycastle project in a shared project ? In this way we have only one project (valid for portable and not) and one dll as result.

You mean merging NBitcoin et NBitcoin.BouncyCastle ?

Actually I forgot about this project at all, I thought I already integrated it into NBitcoin project.
I think if I did not do it because it made the project slow to compile. Ideally I'd like to remove everything that the project does not use, but I sadly did not had time to do it.

The OpenSLL bug is replicated in the method CheckSig of the script evaluator.

**Comment by andbene72** [comment]
I mean using "shared project" a new feature of vs2015 to sharing code across different platforms  http://www.c-sharpcorner.com/UploadFile/7ca517/shared-project-an-impressive-features-of-visual-studio-201/
I think this can be a good way to have one dll but keep BC sources in a separated project.
Well as soon as I have completed tests I will send you a commit, only source update, non project organizational change.

**Comment by NicolasDorier** [comment]
ah wow that's cool. I think it exist for visual studio 2013, because I already heard about it, and remember using it but I don't know for what and when I did that. (probably when I did android/ios dev with xamarin)

I should head cut the BouncyCastle classes I don't use also. A way of doing that would be that I run my tests with coverage on.

**Comment by NicolasDorier** [comment]
https://github.com/MetacoSA/NBitcoin/pull/153
