### ISSUE TITLE
X509Certificate2 dependency removal

### ISSUE THREAD

**Issue by bdangh** [MetacoSA/NBitcoin#157]
It was an good idea to remove dependency to X509Certificate2 because of multi-platform support, but after this certificate cannot be kept in Windows Certificate Store as not exportable.

In my opinion, for Windows there should be some extension which still will receive X509Certificate2 for signing.

**Comment by NicolasDorier** [comment]
Where is there dependency to it ?

The only dependency I remember was in the BIP70 code. Because of that BIP70 feature were not available in portable libraries. I changed that recently so that BIP70 classes are isolated from plateform specific classes. (And I also removed dependency to protobuf-net)

**Comment by bdangh** [comment]
No, issue is not removing dependency. Previously MerchantCertificate was X509Certificate2, also X509Certificate2 was a parameter for the Sign method. 

After you have changed both to byte[] it's not possible to keep signing certificate inside of Certificate Store on the server, so you need raw file. Another issue is now developer should be aware that MerchantCertificate will not extract Public Key anymore before sending answer to the client.

**Comment by NicolasDorier** [comment]
Ah understood, will fix it today.

**Comment by NicolasDorier** [comment]
fixed on https://github.com/MetacoSA/NBitcoin/commit/76540739c72227a9765b5077471550d54e3dafee pushed on version 3.0.0.25
