### ISSUE TITLE
RPCResponse#Result access modifier

### ISSUE THREAD

**Issue by bijakatlykkex** [MetacoSA/NBitcoin#178]
Hello,

The access modifier for RPCResponse#Result has changed from public to internal in one of the latest commits.

RPCClient#SendCommandAsync still returns RPCResponse, so who ever uses the method, will no more have access to Result of command; for example this RPCResponse#Result is required for "gettxout" and "generate" (RegTest mode) which seems not supported by NBitcoin, yet.

**Comment by NicolasDorier** [comment]
I did that before yestersday, because I don't want to expose any Newtonsoft Json type externally. Because in portbale library Newtonsoft is included into NBitcoin and I don't want any conflict if the importing project also have its own Newtonsoft version.

I understand the need to have result public though. What about Result becomes a string instead of JToken ?

**Comment by NicolasDorier** [comment]
Fixed with e6a454efa6c8cbf65a95ea8fe92b4f743a0a87db, I released a new nuget package.
