### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by lismore** [MetacoSA/NBitcoin#267]
Hi,

I have used your NBitcoin Library followed a few examples and seen some progress. 

![image](https://user-images.githubusercontent.com/1145888/28989793-98bcd5c6-796f-11e7-8bec-4c128ee27825.png)

I am a little confused now, is this application now some how syncing to the blockchain like Bitcoin Core or is it using some other way to get data of the blockchain.  

Do I need to run my own full bitcoin core node now with an RPC interface to work with this library. 

Thanks Patrick

**Comment by NicolasDorier** [comment]
If you use QBitNinja then you depends on a block explorer. This has some risk because you depends on how available it is, and on its own interpretation of consensus.

The advantage is that you don't need a bitcoin core node running, and you can query way more stuff than you can with bitcoin core, and you don't need to worry about having a sync node.

You can connect to your own Bitcoin Core node with NBitcoin with the `RPCClient` class.

I advise you to depends on Bitcoin Core for the most you can, and if you find out that Bitcoin Core is not enough for you, then you should host your own Block Explorer. (QBitNinja is open source, but must be hosted on Microsoft Azure)

**Comment by lismore** [comment]
Got it, thanks
