### ISSUE TITLE
NBitcoin.Altcoins How to change byte version programmatically?

### ISSUE THREAD

**Issue by bazooka70** [MetacoSA/NBitcoin#388]
Is there any way to change the the `Base58Type.PUBKEY_ADDRESS` and `Base58Type.SCRIPT_ADDRESS` after you call `NBitcoin.Altcoins.BCash.EnsureRegistered()`?

I mean the bytes that are set in `NBitcoin.Altcoins/BCash.cs -> RegisterLazy()`:

```
// See https://support.bitpay.com/hc/en-us/articles/115004671663-BitPay-s-Adopted-Conventions-for-Bitcoin-Cash-Addresses-URIs-and-Payment-Requests
// Note: This is not compatible with Bitcoin ABC
.SetBase58Bytes(Base58Type.PUBKEY_ADDRESS, new byte[] { 28 })
.SetBase58Bytes(Base58Type.SCRIPT_ADDRESS, new byte[] { 40 })
```

I'm not sure what the implications of using **Copay** format for these bytes, and would prefer to use the legacy base58 format for the public address as default.

I originally used the format from ABC consensus:

```
.SetBase58Bytes(Base58Type.PUBKEY_ADDRESS, new byte[] { 0 })
.SetBase58Bytes(Base58Type.SCRIPT_ADDRESS, new byte[] { 5 })
```

I don't want to use a patch and prefer to use your packages and don;t want to break anything you did. Is it somehow possible to change these bytes at run-time?

I  would really love to hear your thoughts about this. can there be implications when using Copay format? will a transaction be able to go throw to a ABC wallet?

Thanks.

**Comment by NicolasDorier** [comment]
The reason I don't use 0 and 5 is because too much people lost money by sending bitcoin to bcash addresses. Also they are now using a `bitcoincash:` address from now which is not at all Base58, so you will need a hack anyway.

If you really want to do this, allow a way to customize it before calling `EnsureRegistered` and make a PR.

**Comment by bazooka70** [comment]
> The reason I don't use 0 and 5 is because too much people lost money by sending bitcoin to bcash addresses.

You might have a point there. but I'm going to present the `bitcoincash:` address to the end user anyway. he will know nothing bout the base58 address behind the scenes. 

How about a simple public method in the `Network` class:

```
public SetVersionBytes(Base58Type type, byte[] bytes)
{
    base58Prefixes[(int)type] = bytes;            
}

```

**Comment by NicolasDorier** [comment]
Lot's of code depends on Network being immutable I don't want to do this.
I have an idea to be able to extend how to create `Network`.

**Comment by NicolasDorier** [comment]
I think the best is that I provide a way to support bitcoincash: address in NBitcoin. This may be possible to add extensions point to Network to do this.

**Comment by bazooka70** [comment]
Well you do have the public `Network._MagicBytes` :-P
I'm not saying this method is for everyone. only ones who know exactly what they are doing...

**Comment by bazooka70** [comment]
`What if I provide a way for NBitcoin to support the bitcoincash: stupid format? would that do the trick for you ?`

Maybe. It will be great in any case. I already did most of the work with the converting stuff.

I haven't actually tried to create a transaction in the main net ( I need to arange some real bcash to play with). But I strongly think that the raw transaction uses the base58 script pub key. I need to check that issue. and yes, I agree it's totally stupid to have 3 addresses formats :/

**Comment by NicolasDorier** [comment]
Working on it... will take your stuff.

**Comment by NicolasDorier** [comment]
@bazooka70 ok I modified NBitcoin so shitcoin can set their own address scheme! I used your code, thanks a lot. (version 4.1.0.5 which should be soon up)

**Comment by bazooka70** [comment]
Thanks! 
"BTrashAddress" ... is the trash meant to be e.g. "destroy" or e.g. "garbage"? lol

**Comment by NicolasDorier** [comment]
they really need to thank you... I would not have bothered

**Comment by bazooka70** [comment]
Yeah, but who knows , maybe some day BCH can be a normal alternative to the shitty Bitcoin with insane fee rates and transactions that takes more than 2 hours to confirm!

**Comment by NicolasDorier** [comment]
The fees are 5 cents for 10 minutes now. Dogecoin/Litecoin are probably better suited.

**Comment by NicolasDorier** [comment]
I will not use legacy base58 format, this is bitcoin's one. The Bitpay one is supported though.

If you want the legacy one you can use `btrashAddress.ToNetwork(Network.Main)` which will convert this address into a bitcoin address. Though in this case the encapsulated Network will be the one of bitcoin.

**Comment by bazooka70** [comment]
OK, I will run some tests with different wallets and get the conclusions.

BTW, 
> The fees are 5 cents for 10 minutes now.

Here is a simple real transaction I made yesterday:
https://blockchain.info/tx/f4e871460ca4a5b707823376429050ce710197a3f0ef9711660c5a5a62d0a32e

Yes, the fee was low (~0.02 USD) it was estimated via 6 blocks. it took more than 3 hours to confirm! 
so I don't know  where you got that information...

**Comment by bazooka70** [comment]
@knocte,  I mean  that the fee rate per KB was based on 6 blocks. (`estimatesmartfee 6`)
And sorry, I was mistaken it was not 3 but ~7 hours to get 1 confirmation.
This is unreasonable.
I know I'm off topic here (sorry for that) but take a look here also:
[Bitcoin is DEAD for small payments](https://bitcointalk.org/index.php?topic=2618783.0)

**Comment by NicolasDorier** [comment]
so just pay 6 cents, get confirmed in 10 min.

**Comment by knocte** [comment]
Well, that thread starts in December 2017 when the fees were incredibly high. These days fees are super low, and I'm not sure how much of it is because someone decided to stop spamming the network or because the reduced usage of bitcoin (but if it was the latter, then surely other cryptocurrencies may have taken over the lost volume?). Anyway, we can just side-step this debate altogether by concentrating on Layer2 technologies (e.g. Lightning), which will work even in scenarios in which fees are super high like in December last year.

AFAIU b-trash is much under-developed in this area because it hasn't adopted the transaction malleability fix of SegWit that, suffice is to say, is battle-tested already at this point. I've heard that malleability-fixage in b-trash will (or is) done via FlexibleTransactions, but TBH I don't want to know how battle-tested is that, let alone peer reviewed.

**Comment by bazooka70** [comment]
@NicolasDorier, 
> so just pay 6 cents, get confirmed in 10 min.

I don't control this. This tx was made with our system. with standard fee rate of 6 blocks and priority with 2 blocks. all the fee calculation is done via `NBXplorerClient.GetFeeRate(blockCount, fallbackFeeRate).FeeRate;` 

I could pay a **custom** 6 cents or whatever. But how will the **average wallet user** can determine or be aware of that? I need to present him/she /it some standardized fee rates.

**Comment by NicolasDorier** [comment]
I mean just replace the `blockcount` from 6 to 1. It will probably give you 6 cents.

`I would except that crypto transactions will take no more than a few seconds`. That is the trick in crypto, there is no finality. 

In crypto you can never say "this transaction is complete", because everything can be reorg. You can pretend it is paid as soon as it reaches the blockchain, and verify at shipping time that the transaction is still here. (this is what merchant does)

If you want instant transaction finality then you only have Lightning Network capable of achieving this. But this is a bit early.

**Comment by bazooka70** [comment]
Something is wrong or not synced with the NBXplorer version I just downloaded. the RPC with main bch fails b/c the address issue.  in the `RPCArgs.cs` TestRPCAsync:

> The RPC Server is on a different blockchain than the one configured for tumbling

i.e. the address returned in NBXplorer is the Copay format. and `validateaddress` fails. I think your new trash format will work just fine, since it validates OK in the core.

**Comment by NicolasDorier** [comment]
oh shit yeah, I disable this test during the unit tests so Imightnot have caught it. Let me check.

**Comment by NicolasDorier** [comment]
I should have fixed it now, give it a try.

**Comment by bazooka70** [comment]
Cool, thanks. it seems to work OK now.

**Comment by bazooka70** [comment]
> I mean just replace the blockcount from 6 to 1. It will probably give you 6 cents.

I might look into RBF enabled transactions. I think NBitcoin supports it? So if a tx is stuck like it was for me, I could at-least give  the option to bump the fee...
