### ISSUE TITLE
Stop needlessly disrespectful behavior towards certain cryptocurrency projects

### ISSUE THREAD

**Issue by GSPP** [MetacoSA/NBitcoin#433]
Bitcoin Cash and Bitcoin Gold are sometimes referred to as BCash, BGold and "trash" by this project. This happens in the commit logs as well as in the code. Constants are being called `BCash` for example and there actually is a `public class BTrashAddress`.

I will not argue for or against the merit of these cryptocurrencies. But it would behoove this project to not engage in unnecessarily disrespectful behavior towards these currencies. This kind of behavior is unhelpful to the standing the NBitcoin project has in the community. It is unhelpful to the cryptocurrency ecosystem at large because it is divisive. It's also confusing on a technical level because it makes the library harder to use.

Also consider that these actions are now forever documented due to the immutable nature of Git. The people who engaged in this kind of behavior under their real name might regret this in the future without the ability to undo it.

It is a very useful feature of NBitcoin to support altcoins to a certain extent. Give each of them the same fair chance and respect.

**Comment by NicolasDorier** [comment]
Calling Bitcoin Gold `BGold` is not a mark or disrespect. Naming their coin with Bitcoin in the name is. They have nothing to do with Bitcoin.

Only disrespect is for BTrash, on which I spent my time for free to support them, while all other crypto currencies added their own support.
Beggars can't be chooser. This won't be fixed.

**Comment by nopara73** [comment]
The only reason to call it "Bitcoin something" is to hijack the brand of Bitcoin and thus disrespect Bitcoin developers and the whole Bitcoin community. Please @GSPP call BCH to BCH, as to both of us avoid disrespecting each other's coins.  

https://medium.com/@nopara73/is-it-bitcoin-cash-or-bcash-acd234431577

**Comment by bazooka70** [comment]
I was the original author to add BCH support in NBitcoin, and  dealing with their shitty address which really was **inconclusive** and had 3 possible formats, was a pain! 
the legacy base58 conflicted with the Bitcoin addresses and there was (and still is in some wallets) a potential danger to lose your funds by sending them to the wrong chain. this does not happen in any other coin I know of.

I can only agree with the `BTrash` naming part, but hey, I'm not the author, and eventually everyone can enjoy it for **free**. 
I guess it was because @NicolasDorier spent a LOT of his time dealing with this issue, but finally made the right choice to disable the legacy address completely (which I first disagree). other issues with BCH  network were also solved thanks to Nicolas and no one else. the BCH dev was not responsive at all.

**Comment by OverlordQ** [comment]
What 'BCH dev'? ABC devs? Unlimited Devs? Somebody else?

**Comment by R2D221** [comment]
> If anything they should thank me.

I don't know. I wouldn't expect people thanking me if I called their project “trash”. What's this, elementary school?

You were not obligated to add support for it. That was the respectful thing to do.

**Comment by NicolasDorier** [comment]
And they can fork NBitcoin if the disrespect bother them.

**Comment by R2D221** [comment]
I mean, they did. I'm sure you get a notification when a fork happens.
