### ISSUE TITLE
Base58 WIF format not always returning 5-prefixed strings for MainNet?

### ISSUE THREAD

**Issue by knocte** [MetacoSA/NBitcoin#443]
According to https://en.bitcoin.it/wiki/Private_key#Base58_Wallet_Import_format , WIF strings should be 51 characters long and start with "5" for MainNet.

However, I'm not getting this result with the latest NBitcoin:

```
byte[] privKey = SomeFunction();
// this prints 32
Console.WriteLine("Length:" + privKey.Length);
// this prints 6F2552E159F2A1E1E26C2262DA459818FD56C81C363FCC70B94C423DEF42E59F
Console.WriteLine(BitConverter.ToString(privKey).Replace("-", ""));

var key = new Key(privKey);
//this prints KzwmFdCY1PcZTaf13BYzTHfry6Sgk9mMcqQKrJ2iVkcmFwU5PyFq
//but it should print 5JfEekYcaAexqcigtFAy4h2ZAY95vjKCvS1khAkSG8ATo1veQAD
Console.WriteLine(key.GetWif(NBitcoin.Network.Main).ToWif());
```

What am I doing wrong here?

There are more test vectors like this in https://github.com/keybase/warpwallet/blob/master/test/spec.json (I picked the first one for this example).

Thanks

**Comment by lontivero** [comment]
You should create it with `new Key(privKey)`. The compressed parameter is not for the key itself, after all a key is simple a number and cannot be compressed, it is for the pubkey's representation that you get from the key. The pubkey is a point in the elliptic curve with coordinates (x, y) and that point can be "compressed" because `y=f(x)` so, if you know `x` and `f` the `y` is redundant (that's what we talk about when we say "compressed" pubkey (quite silly, isn't it?)

Given compressed pubkeys are smaller than theirs uncompressed version (both represent the same EC point after all) the former are used and the later are "deprecated" (i don't find a better word to describe the situation).

Always use the compressed version at least you are trying to stole the Satoshi's coins ;)

**Comment by knocte** [comment]
> You should create it with new Key(privKey). The compressed parameter is not for the key itself, after all a key is simply a number and cannot be compressed, it is for the pubkey's representation that you get from the key. 

Hey Lucas! Not sure I understand your point, because if I use `new Key(privKey)` then the WIF representation of my private key doesn't start with "5", so it doesn't follow the standard. Is this an NBitcoin's bug?

**Comment by lontivero** [comment]
@knocte I'm sorry, I didn't read your question really well before answering it. You're right of course, if we want to get an uncompressed pubey then yes, you have to use the .ctor `new Key(privKey, 32, false)` as you well said. In that case the serialized BitcoinSecret (key + network) will be serialized as and 51 length string started with `5`.

However, that is pretty unusual and you should work with uncompressed pubkeys. If you use the .ctor `new Key(privKey)` as I told you before then, you will get a compressed pubkey. In that case the serialized BitcoinSecret will be serialized as a 52 length string started with `K` (or `L`) as you got before.

I don't know what you want to achieve but by general rule you shouldn't use uncompressed pubkeys (at least you know what you are doing and want to deal with old txs). In other words, you should use compressed pubkeys and the WIP representation of your keys should start with K (or L) for mainnet.

Finally, no, there is no bug in NBitcoin regarding to this, it works as expected. In case you don't understand me (my English sucks hard) read about compressed and uncompressed keys because that's what you don't fully understand it seems to me.

**Comment by knocte** [comment]
> In that case the serialized BitcoinSecret will be serialized as a 52 length string started with K (or L) as you got before.

I don't mind working with uncompressed pubkeys, so long as my private keys follow the standard. I don't see any documentation about K/L prefixes, is  https://en.bitcoin.it/wiki/ outdated?

> I don't know what you want to achieve

I can tell you what I want(ed) to achieve: warpwallet implementation in .NET, which I already did via `new Key(privKey, 32, false)` (see full commit in my wallet if you're curious: https://github.com/knocte/gwallet/commit/1f5c6c6fe9fe2decefe5698ccb1a77bd01054248 ). What I wanted is an implementation that matches exactly, so I also added unit tests, which come from the original javascript implementation: https://github.com/keybase/warpwallet/blob/master/test/spec.json . Those test vectors have base58-encoded private keys starting with "5". Is their implementation obsolete...?

**Comment by lontivero** [comment]
> I don't mind working with uncompressed pubkeys, so long as my private keys follow the standard.

Uncompressed pubkeys are standard and "deprecated" (nobody has used them in years). Compressed pubkeys are also standard and recommended.

>  I don't see any documentation about K/L prefixes, is https://en.bitcoin.it/wiki/ outdated?

It is not outdated. It says it clearly:
>>> For **private keys associated with uncompressed public keys**, they are 51 characters and always **start with the number 5** on mainnet (9 on testnet). **Private keys associated with compressed public keys** are 52 characters and **start with a capital L or K** on mainnet  

>  Is their implementation obsolete...?
In my opinion it is. Because uncompressed keys are something that was common before 2012/2013. 

I'm not saying your wallet shouldn't handle uncompressed keys propertly. What I say is they are very old and uncommon in these days.

**Comment by knocte** [comment]
> It is not outdated. It says it clearly:

OMG I'm blind, sorry. Thanks for your patience.

> In my opinion it is.

Yeah, and the public addresses they generate are not segwit. So in the end I've decided to use compressed keys in my wallet (to gain WarpWallet algorithm support, even if it doesn't integrate well with their current webwallet*).

Sorry for the noise, closing.

* -> This way, I also avoid encouraging anyone to input private seeds in websites.
