### ISSUE TITLE
P2PK addresses

### ISSUE THREAD

**Issue by AntoineXBTO** [MetacoSA/NBitcoin#504]
Hi,

Why is there no way to create an address from a P2PK script?

For example, how to transform this script
`020e46e79a2a8d12b9b5d12c7a91adb4e454edfae43c0a0cb805427d2ac7613fd9 OP_CHECKSIG`
into 
`1P3rU1Nk1pmc2BiWC8dEy9bZa1ZbMp5jfg`
as displayed by a bitcoin core node.

GetDestinationAddress won't create it and it doesn't seem like there is a function to create one from the public key I can extract from the script.

**Comment by lontivero** [comment]
That's because P2PK scripts were before than bitcoin addresses, that's why p2pk cannot be represented by bitcoin address. In fact, if you send bitcoins to that address `1P3rU1Nk1pmc2BiWC8dEy9bZa1ZbMp5jfg`, you will not be able to spend it with the private key which your public key (`020e46e79a2a8d12b9b5d12c7a91adb4e454edfae43c0a0cb805427d2ac7613fd9`) was derived from. 

Just to show were that bitcoin address come from:
```c#
Console.WriteLine(
    new Script("020e46e79a2a8d12b9b5d12c7a91adb4e454edfae43c0a0cb805427d2ac7613fd9 OP_CHECKSIG")
    .GetDestinationPublicKeys().First()
    .GetAddress(Network.Main);
    .ToString());
```

It you follow this code you will see that it exract the first public key in the script (the only one there) and then it hashes it and **creates a p2pkh address!**. By carefull with this.

**Comment by AntoineXBTO** [comment]
It works thanks!

**Comment by lontivero** [comment]
Just for the record: i didn't provided you a solution. I've just gave you an explanation about why that piece of code is 100% WRONG and can make you loose money (you shouldn't use it at all).

**Comment by AntoineXBTO** [comment]
This code is simply to be able to display an address from a script and won't be used to create new addresses (and send money to them). I understand this is not a correct way to create addresses but it looks like this is the way bitcoin core chose to display old P2PK scripts.
