### ISSUE TITLE
PayToScriptHashTemplate matches incorrectly on a pay to pubkey TxIn

### ISSUE THREAD

**Issue by GSPP** [MetacoSA/NBitcoin#571]
When `PayToScriptHashTemplate.Instance.ExtractScriptSigParameters(script)` is executed on TxIn 7 of [this transaction](https://www.blockchain.com/btc/tx/3a5c037f79eda4d61925529dd68951b92c11642b224f0ff3230c4a79f117e8f6) the template matches. It should not match since this is a pay to pubkey TxIn.

I believe that P2SH TxIns always start with `OP_0` which should allow the template to distinguish the cases and only match on true P2SH TxIns.

**Comment by NicolasDorier** [comment]
This is not a mistake. It is not possible to know if a specific scriptSig is P2SH just by looking at it.

The template is using an heuristic where it takes the last push of the transaction, and check if this seems to be a valid script. This happen to be the case time to time by chance.

`public PayToScriptHashSigParameters ExtractScriptSigParameters(Script scriptSig, Script scriptPubKey)` is better, because thanks to the scriptPubKey, I can check that the hash in the scriptPubKey is the same as the hash of the last elements in the scriptSig, and thus determine in this is really P2SH.

**Comment by GSPP** [comment]
I see. So it is not possible to determine if a TxIn spends a P2SH TxOut just from the Tx data itself. The previous Tx is required. Thanks for explaining.

For reference: https://github.com/bitcoin/bips/blob/master/bip-0016.mediawiki

**Comment by NicolasDorier** [comment]
@GSPP one tip though: If your TxIn has a WitScript (non null / with length !=0), then it is necessarily a P2SH.
