### ISSUE TITLE
Dash default cookiefile path not well configured

### ISSUE THREAD

**Issue by NicolasDorier** [MetacoSA/NBitcoin#580]
@bdangh, you have not properly set the default cookie path for Dash. Can you fix it? (you can repro by running dash without parameter and trying to use `new RPCClient(Dash.Regtest)`)

**Comment by snogcel** [comment]
To add to @NicolasDorier's comment, I've reviewed this and see one potential issue that I wanted to raise to @bdangh on https://github.com/MetacoSA/NBitcoin/blob/dd1cc8cbcd5b011f397664aa9e645cbb4d4538bf/NBitcoin.Altcoins/Dash.cs#L123. The default data folder should be ".dashcore" / "DashCore" instead of ".dash" / "Dash".

**Comment by bdangh** [comment]
Hey guys, I actually didn’t check implementation with cookies and I don’t know much how they work. Should I just replace ".dash" with ".dashcore" in the line @snogcel pointed to?

**Comment by NicolasDorier** [comment]
Seems so. Cookie are used when you don't set user/pwd for RPC connection. So you have less stuff to configure for things to just work.

**Comment by bdangh** [comment]
I guess I know where is the issue, I guess registring default cookie part should be should be same as with other alts with “dashcore” folder name (it is different at the moment for some reason), I will fix and test it tomorrow.

**Comment by NicolasDorier** [comment]
https://github.com/MetacoSA/NBitcoin/pull/581
