### ISSUE TITLE
Adding two Public Key 

### ISSUE THREAD

**Issue by wasimjee** [MetacoSA/NBitcoin#716]
How can i add two public key or two private key

Example

PublicKey3 = PublicKey1 + PublicKey2

PrivateKey3 = PrivateKey1 + PrivateKey2

**Comment by wasimjee** [comment]
Or , even if possible to multiply the Private Keys

**Comment by joemphilips** [comment]
I think it is impossible in current implementation.
I had the same problem since it is necessary in the Lightning Network.
In my case I added a method like this in my own fork.

`PubKey.cs`

```csharp
               public PubKey Add(PubKey pk)
              {
                       var pub1 = _ECKey.GetPublicKeyParameters();
                       var pub2 = pk._ECKey.GetPublicKeyParameters();
                       var q = pub1.Q.Add(pub2.Q).Normalize();
                       if (q.IsInfinity)
                               throw new InvalidOperationException("result of addition has become ");
                       var newPubKey = ECKey.Secp256k1.Curve.CreatePoint(q.XCoord.ToBigInteger(), q.YCoord.ToBigInteger());
                       return new ECKey(newPubKey.Normalize().GetEncoded(true), false).GetPubKey(true);
               }
```

Also private key multiplication.

`Key.cs`

```csharp
		public Key Multiply(Key value)
		{
			var left = new BouncyCastle.Math.EC.Custom.Sec.SecP256K1FieldElement(value._ECKey.PrivateKey.D);
			var right = new BouncyCastle.Math.EC.Custom.Sec.SecP256K1FieldElement(this._ECKey.PrivateKey.D);
			var newD = left.Multiply(right);
			return new Key(newD.GetEncoded());
		}
```

I might send a PR later. but not sure when. This is just a stub implementation and needs more test before merging,

**Comment by wasimjee** [comment]
Thanks Philips, I will go through it

**Comment by lontivero** [comment]
I would like to highlight that this topic shouldn't be taken lightly. There are many things to have in mind when you operates with key material. Just a few:

### About private keys:

* We use to say that private keys are just scalar numbers and then multiply them private keys is something trivial but, it is NOT. First, there are two values you have to be sure that you are handling well: zero (0) and one (1), this is for obvious reasons but a relaxed approach could lead to lose of money.
* You have should validate the private keys are valid [1, n) where 'n' is the order of the curve.
* You have to remember operations with private keys are mod n.

@joemphilips operates private keys with `SecP256K1FieldElement` (Finite Field mod Q for secp256k1 curve). That's wrong because the coordinates (both **x** and **y**) for the points in the EC are defined in the FF but the private keys are, as I said above, mod N. Given **Q > N**, it could one day return an invalid private key.

### About public keys

The manipulation of public keys is also a factor of risk you have to take into account. You have to validate that the public keys are **valid**, this is, they are satisfy the EC ecuation (they are real points in the curve). Given I don't know what you want to do I cannot say much more but you should ask some cryptographer to validate your idea and review your implementation.

**Comment by NicolasDorier** [comment]
Ping @EthanHeilman is it something you would be confident reviewing if we do it?

**Comment by knocte** [comment]
Isn't this formally called "threshold keys"? one would be able to do multi-sig without anyone knowing.

**Comment by wasimjee** [comment]
I have checked.

The addition of Public Key is working fine.

But the Multiplication of the Private Key is not correct.

Even I have tried to add the private key, still not giving the correct result

**Comment by lontivero** [comment]
@wasimjee this is not a cryptography forum. If you post some code (NBitcoin related) we can review it but says "Multiplication of the Private Key is not correct" makes no sense.

**Comment by EthanHeilman** [comment]
@NicolasDorier I'd be happy to review this if you build it because I'm learning elliptic curve cryptography but I'm *not* an expert in elliptic curve cryptography. This stuff is really dangerous and hard to get right. You need an expert to review this. My review would not be sufficient.

I'd recommend someone that worked on the [secp256k1](https://github.com/bitcoin-core/secp256k1) library for instance @sipa, @gmaxwell, @apoelstra ...

**Comment by NicolasDorier** [comment]
thanks, will ping them then if I do it.

I am wondering if we should do it at all in this library though. Because even if we do it correctly, the chances that somebody use it incorrectly is high.

**Comment by lontivero** [comment]
IMO there are many things that would be nice to have available for experimentation and that shouldn't be part of NBitcoin. For example: the pedersen commitments, schnorr bindling signatures and key maths.

**Comment by sipa** [comment]
Just vaguely skimming this thread, if you happen to be using BouncyCastle, I'm not particularly worried about bugs in elliptic curve implementation, @peterdettman (one of the main authors of BouncyCastle) also contributed several improvements to libsecp256k1.

However, correctly using protocols that rely on manipulating EC keys directly are _very_ tricky (especially if you're using them to achieve some kind of threshold/multisig signatures). This isn't specific to EC math, as the same issues would arise from using other DLP-based schemes.

**Comment by NicolasDorier** [comment]
Thanks for the feedback all. I close this. NBitcoin is not a cryptographic library, and people should just directly depends on BouncyCastle instead of NBitcoin if they want to do something more complicated like EC calculations.

"Adding public keys" or "Adding private keys" are not good semantic that a developer non well versed in cryptography should use. (NBitcoin does not assume cryptographic knowledge beyond key/public key or signature concepts) 

If any calculation is needed, it should be multiplying "field elements" or "EC point", done by somebody who knows what he is doing at the math level.

**Comment by EthanHeilman** [comment]
>"Adding public keys" or "Adding private keys" are not good semantic that a developer non well versed in cryptography should use.

This is the right choice.
