### ISSUE TITLE
Better understanding and explanation 

### ISSUE THREAD

**Issue by okarpov** [MetacoSA/NBitcoin#784]
Hello,

I have such piece of code and need to understand the following:
- how to transfer exact amount of coins?
- who pays transaction fee?
- what is minimum fee?
- how to calculate fee?
- what is SendEstimatedFees?

`NBitcoin.TransactionBuilder x = new NBitcoin.TransactionBuilder();
                x.StandardTransactionPolicy.MinRelayTxFee = new FeeRate(0);
                x.AddCoins(aliceCoins);
                x.AddKeys(private_keys.ToArray());
                x.SetChange(alices[0].GetAddress());

                for (int i = 0; i < satoshies.Length; i++)
                {
                        x.Send(satoshies[i], new Money(ToAddressAmount[i].amount));
                }

                if (substractfees) x.SubtractFees(); 

                if (send_change_to_owner)
                {
                    BitcoinPubKeyAddress addr = new BitcoinPubKeyAddress(LTC_ADDRESS, NBitcoin.Network.GetNetwork("ltc-main"));
                    x.SetChange(addr);
                }
                else x.SetChange(alices[0].GetAddress());

                FeeRate feerate = new FeeRate(new Money(40000));

                try
                {
                    x.SendEstimatedFees(feerate);
                }
                catch (Exception ex)
                {
                    LogError(ex.Message);
                }

                NBitcoin.Transaction tx = x.BuildTransaction(false);

                FeeRate fr = new FeeRate(22800); 
                for (int i = 0; i < tx.Outputs.Count; i++)
                {
                    Money dust = tx.Outputs[i].GetDustThreshold(fr);
                    if (tx.Outputs[i].IsDust(fr) && tx.Outputs[i].Value.Satoshi < 1000)
                    {
                        tx.Outputs.RemoveAt(i--);
                    }
                }
                x.SignTransactionInPlace(tx);`

**Comment by NicolasDorier** [comment]
Don't use `NBitcoin.TransactionBuilder x = new NBitcoin.TransactionBuilder()` but `Network.Main.CreateTransactionBuilder()` for example.

All of those methods have doc attached to it you should see if you use Visual studio or Visual Studio code...

* `SendEstimatedFees` send the fees based on the fee rate. This is `estimated` because the reality might be slightly different as it is impossible for me to know the size of the transaction before it is signed.
* `MinRelayTxFee` is a fee where, if you pay less than this, your transaction won't be broadcasted on the network. Better not changing it as you want to check for this.
* You don't calculate fees, you use `SendEstimatedFees`, build the transaction then can use `var fee = tx.GetFee(transactionBuilder.FindSpentCoins(tx));` if you want it in satoshi term.
* `how to transfer exact amount of coins?` . txbuilder.Send(amount,dest)

Read https://programmingblockchain.gitbook.io/programmingblockchain/ to better understand the concepts.

**Comment by okarpov** [comment]
Thank you for explanation but current problem with all of that is that the current code sends less amount or greater amount of coins

and im not sure who pay fee sender or receiver? 

if (substractfees) x.SubtractFees(); 

Thank you

**Comment by NicolasDorier** [comment]
if you call `SubtractFees` it means that the last destination you sent to via `Send` will pay the fee.
If you don't call the exact amount will be sent.

**Comment by okarpov** [comment]
that is what I thought but it seems not - will check one more time. 

How to increase fee to speed up the processing of transactions (in scope of the my code)? 

thx

**Comment by NicolasDorier** [comment]
@okarpov aren't you sending several time to the same destination? if so, those are grouped into a single output.

If you want more fee increase `feerate`.

Remove

```csharp
      FeeRate fr = new FeeRate(22800); 
            for (int i = 0; i < tx.Outputs.Count; i++)
            {
                Money dust = tx.Outputs[i].GetDustThreshold(fr);
                if (tx.Outputs[i].IsDust(fr) && tx.Outputs[i].Value.Satoshi < 1000)
                {
                    tx.Outputs.RemoveAt(i--);
                }
            }
```
